// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI9qvYMfohaVJMyw8Y2S6Cg2s6-x9lWgE',
    appId: '1:1049190215747:web:6f62e4cbfb0d2dd32c24f6',
    messagingSenderId: '1049190215747',
    projectId: 'ecotrack-bea',
    authDomain: 'ecotrack-bea.firebaseapp.com',
    storageBucket: 'ecotrack-bea.firebasestorage.app',
    measurementId: 'G-WZ8NKSST86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeS3niHnUKjmz8ZDH1NQ5QTNb-NxMJjOc',
    appId: '1:1049190215747:android:78533eb8a294fc012c24f6',
    messagingSenderId: '1049190215747',
    projectId: 'ecotrack-bea',
    storageBucket: 'ecotrack-bea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB03LodatCkybjePpzh4pt_nPkEp0merU',
    appId: '1:1049190215747:ios:c872f1f186c521562c24f6',
    messagingSenderId: '1049190215747',
    projectId: 'ecotrack-bea',
    storageBucket: 'ecotrack-bea.firebasestorage.app',
    iosBundleId: 'com.example.testezin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB03LodatCkybjePpzh4pt_nPkEp0merU',
    appId: '1:1049190215747:ios:c872f1f186c521562c24f6',
    messagingSenderId: '1049190215747',
    projectId: 'ecotrack-bea',
    storageBucket: 'ecotrack-bea.firebasestorage.app',
    iosBundleId: 'com.example.testezin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCI9qvYMfohaVJMyw8Y2S6Cg2s6-x9lWgE',
    appId: '1:1049190215747:web:7e29b040b832667e2c24f6',
    messagingSenderId: '1049190215747',
    projectId: 'ecotrack-bea',
    authDomain: 'ecotrack-bea.firebaseapp.com',
    storageBucket: 'ecotrack-bea.firebasestorage.app',
    measurementId: 'G-NLXY5GP2EC',
  );
}
